"""EevaResearch — Evidence-First Themes MVP (design/DECISIONS.md). A
private, operator-only authoring and publishing tool for one curated,
public-facing ResearchTheme. Not a product feature: no application
runtime module (app.py, any src/ui page) imports this script, and it is
never invoked automatically by anything in this repository.

Invoke as (from the repo root):

    python -m scripts.create_theme --confirm [--backend json|sqlite|postgres]
    python -m scripts.create_theme --set-visibility <theme_id> <new_visibility> --confirm [--backend ...]

Safety gates for authoring new content (mirrors
scripts/create_research_case.py's own exact contract):

  1. AUTHORING_ENABLED below defaults to False. An operator must
     deliberately edit this file and set it to True before this script
     will ever consider persisting anything.
  2. Even with AUTHORING_ENABLED = True, the `--confirm` CLI flag is
     also required — without it, this is a dry run: build, validate,
     print what would happen, never write.
  3. A content-level placeholder-sentinel scan refuses to persist a
     theme, evidence item, or company-map entry that still contains the
     literal REPLACE_ME string anywhere — independent of the two gates
     above, so this script can never publish the shipped placeholder
     text as if it were real research.

Publishing (moving an existing theme through
internal -> ready_to_publish -> published -> archived) is a SEPARATE,
explicit action via --set-visibility — creating a theme's content and
publishing it are two deliberate operator decisions, never one. Every
visibility change goes through the private curator repository seam
(backend_factory.get_theme_curator_repository) — this script never
touches the public, published-only read protocol, and nothing here
ever automatically publishes a theme from a Research Case or any other
internal object.

No external behavior: no network call, no source fetch/validation, no
LLM/model call, no scanning/discovery, no automatic translation, no
email/notification, no deployment. Every id is derived deterministically
from operator-authored content (see src.data_access.theme_store's own
ID factories) — re-running this script with identical authored content
is always safe: already-inserted rows are rejected as duplicates with
no mutation, and whatever wasn't yet inserted is added, since there is
no atomic multi-record transaction here (a deliberate, simpler design
than the Research Case bundle writer — themes are low-volume and
manually curated one at a time; see the approved scope's own "minimum
persistence needed" instruction)."""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

from src.config.settings import Settings, get_settings
from src.data_access import backend_factory
from src.data_access.theme_store import build_theme_company_map_id, build_theme_evidence_id, build_theme_id
from src.models.theme_research import (
    CompanyRole,
    EvidenceDirection,
    ResearchTheme,
    ThemeCategory,
    ThemeCompanyMapEntry,
    ThemeEvidenceItem,
    ThemeStatus,
    ThemeVisibility,
)

# =============================================================================
# SAFETY GATE 1 of 2 — see module docstring. Must be hand-edited to True.
# =============================================================================
AUTHORING_ENABLED = False

# A literal sentinel an operator must replace with real, checked content.
_PLACEHOLDER_SENTINEL = "REPLACE_ME"

# The only visibility a freshly authored theme may start at — publishing
# is always a separate, later --set-visibility action.
_INITIAL_VISIBILITY = ThemeVisibility.INTERNAL

# Explicit, narrow visibility state machine for --set-visibility. Any
# transition not listed here is refused with a clear message — this
# script does not trust an arbitrary operator-typed target value.
_ALLOWED_VISIBILITY_TRANSITIONS: dict[ThemeVisibility, frozenset[ThemeVisibility]] = {
    ThemeVisibility.INTERNAL: frozenset({ThemeVisibility.READY_TO_PUBLISH}),
    ThemeVisibility.READY_TO_PUBLISH: frozenset({ThemeVisibility.PUBLISHED, ThemeVisibility.INTERNAL}),
    ThemeVisibility.PUBLISHED: frozenset({ThemeVisibility.ARCHIVED}),
    ThemeVisibility.ARCHIVED: frozenset(),
}

# =============================================================================
# OPERATOR-AUTHORED THEME CONTENT — edit every _PLACEHOLDER_SENTINEL
# value below with real, checked content before setting
# AUTHORING_ENABLED = True. Timestamps must be authored (a real moment
# you are recording this), never generated by this script.
# =============================================================================

_THEME_CATEGORY = ThemeCategory.BOTTLENECK  # edit to the correct category
_THEME_STATUS = ThemeStatus.NEW  # edit to the correct status
_THEME_CREATED_AT = _PLACEHOLDER_SENTINEL  # e.g. "2026-08-20T00:00:00+00:00"
_THEME_TITLE = _PLACEHOLDER_SENTINEL
_THEME_KEY_QUESTION = _PLACEHOLDER_SENTINEL
_THEME_HYPOTHESIS = _PLACEHOLDER_SENTINEL  # one sentence
_THEME_WORKING_THESIS = _PLACEHOLDER_SENTINEL
_THEME_WHY_IT_MATTERS = _PLACEHOLDER_SENTINEL
_THEME_WHAT_COULD_CHANGE_THE_VIEW = _PLACEHOLDER_SENTINEL
_THEME_WHAT_TO_WATCH_NEXT = _PLACEHOLDER_SENTINEL


def _build_evidence_specs() -> list[dict]:
    """One dict per ThemeEvidenceItem to create. Edit/add entries; every
    value must be real, checked content from a working official-source
    URL — never invented. At least one entry is required — a theme with
    zero evidence is not a valid research narrative under this MVP."""
    return [
        {
            "date": _PLACEHOLDER_SENTINEL,  # e.g. "2026-08-15"
            "company": _PLACEHOLDER_SENTINEL,
            "source_name": _PLACEHOLDER_SENTINEL,  # e.g. "SEC EDGAR"
            "source_url": _PLACEHOLDER_SENTINEL,  # must be a real http(s) URL
            "fact": _PLACEHOLDER_SENTINEL,  # the observed fact, not an interpretation
            "relevance": _PLACEHOLDER_SENTINEL,  # why this fact matters to the theme
            "direction": EvidenceDirection.SUPPORTS,
        },
    ]


def _build_company_map_specs() -> list[dict]:
    """One dict per ThemeCompanyMapEntry. May be empty — a group with no
    entries is simply omitted by the UI, never rendered as an empty
    heading."""
    return [
        {
            "company_name": _PLACEHOLDER_SENTINEL,
            "role": CompanyRole.EXPOSED,
            "note": None,
        },
    ]


def build_authored_theme(
    enable_authoring: bool = AUTHORING_ENABLED,
) -> tuple[ResearchTheme, list[ThemeEvidenceItem], list[ThemeCompanyMapEntry]] | None:
    """Pure, no I/O. Returns None when `enable_authoring` is False (the
    default) — the caller must not proceed to validation/persistence in
    that case. `enable_authoring` is a parameter (not a bare module-
    level read) specifically so tests can exercise both branches
    without needing to edit this file."""
    if not enable_authoring:
        return None

    theme_id = build_theme_id(_THEME_TITLE, _THEME_CREATED_AT)
    theme = ResearchTheme(
        id=theme_id,
        category=_THEME_CATEGORY,
        status=_THEME_STATUS,
        visibility=_INITIAL_VISIBILITY,
        title=_THEME_TITLE,
        key_question=_THEME_KEY_QUESTION,
        hypothesis=_THEME_HYPOTHESIS,
        working_thesis=_THEME_WORKING_THESIS,
        why_it_matters=_THEME_WHY_IT_MATTERS,
        what_could_change_the_view=_THEME_WHAT_COULD_CHANGE_THE_VIEW,
        what_to_watch_next=_THEME_WHAT_TO_WATCH_NEXT,
        created_at=_THEME_CREATED_AT,
        updated_at=_THEME_CREATED_AT,
    )

    evidence_items = []
    for spec in _build_evidence_specs():
        evidence_id = build_theme_evidence_id(theme_id, spec["source_url"], spec["date"])
        evidence_items.append(ThemeEvidenceItem(
            id=evidence_id, theme_id=theme_id,
            date=spec["date"], company=spec["company"], source_name=spec["source_name"],
            source_url=spec["source_url"], fact=spec["fact"], relevance=spec["relevance"],
            direction=spec["direction"],
        ))

    company_map_entries = []
    for spec in _build_company_map_specs():
        entry_id = build_theme_company_map_id(theme_id, spec["company_name"], spec["role"])
        company_map_entries.append(ThemeCompanyMapEntry(
            id=entry_id, theme_id=theme_id,
            company_name=spec["company_name"], role=spec["role"], note=spec.get("note"),
        ))

    return theme, evidence_items, company_map_entries


def _nonblank(value: object) -> bool:
    return isinstance(value, str) and value.strip() != ""


def _safe_source_url(url: object) -> bool:
    return isinstance(url, str) and (url.strip().lower().startswith("https://") or url.strip().lower().startswith("http://"))


def contains_placeholder_sentinel(
    theme: ResearchTheme, evidence_items: list[ThemeEvidenceItem], company_map_entries: list[ThemeCompanyMapEntry],
) -> bool:
    values: list[object] = [
        theme.title, theme.key_question, theme.hypothesis, theme.working_thesis, theme.why_it_matters,
        theme.what_could_change_the_view, theme.what_to_watch_next, theme.created_at,
    ]
    for item in evidence_items:
        values.extend([item.date, item.company, item.source_name, item.source_url, item.fact, item.relevance])
    for entry in company_map_entries:
        values.append(entry.company_name)
        if entry.note is not None:
            values.append(entry.note)
    return any(isinstance(value, str) and _PLACEHOLDER_SENTINEL in value for value in values)


def validate_theme_content(
    theme: ResearchTheme, evidence_items: list[ThemeEvidenceItem], company_map_entries: list[ThemeCompanyMapEntry],
) -> tuple[str, ...]:
    """Plain, deterministic content checks — no separate validation
    module exists for Themes (deliberately, per the approved MVP scope);
    this is the minimum needed to keep a curator from publishing
    obviously broken content. Never raises."""
    errors: list[str] = []
    required_theme_fields = {
        "title": theme.title, "key_question": theme.key_question, "hypothesis": theme.hypothesis,
        "working_thesis": theme.working_thesis, "why_it_matters": theme.why_it_matters,
        "what_could_change_the_view": theme.what_could_change_the_view,
        "what_to_watch_next": theme.what_to_watch_next, "created_at": theme.created_at,
    }
    for field_name, value in required_theme_fields.items():
        if not _nonblank(value):
            errors.append(f"theme.{field_name} must not be blank.")

    if not evidence_items:
        errors.append("At least one evidence item is required.")
    for index, item in enumerate(evidence_items):
        for field_name, value in [
            ("date", item.date), ("company", item.company), ("source_name", item.source_name),
            ("fact", item.fact), ("relevance", item.relevance),
        ]:
            if not _nonblank(value):
                errors.append(f"evidence[{index}].{field_name} must not be blank.")
        if not _safe_source_url(item.source_url):
            errors.append(f"evidence[{index}].source_url must be a working http:// or https:// URL.")

    for index, entry in enumerate(company_map_entries):
        if not _nonblank(entry.company_name):
            errors.append(f"company_map[{index}].company_name must not be blank.")

    return tuple(errors)


def persist_theme(
    theme: ResearchTheme, evidence_items: list[ThemeEvidenceItem], company_map_entries: list[ThemeCompanyMapEntry],
    backend: str, cache_dir=None, sqlite_path=None, postgres_url=None,
) -> tuple[bool, list[str]]:
    """Sequential inserts through the private curator repository —
    never the public/UI-facing protocol. Returns (theme_created, notes)
    where notes describes exactly what happened for each record. Safe
    to re-run: every id is content-derived, so an already-inserted
    record is rejected with no mutation rather than duplicated."""
    settings = Settings(
        db_backend=backend,
        cache_dir=Path(cache_dir) if cache_dir else Settings().cache_dir,
        state_db_path=Path(sqlite_path) if sqlite_path else None,
        state_db_url=postgres_url,
    )
    curator = backend_factory.get_theme_curator_repository(settings)

    notes: list[str] = []
    theme_created = curator.insert_theme(theme)
    notes.append(f"theme {theme.id}: {'created' if theme_created else 'already existed (unchanged)'}")

    for item in evidence_items:
        created = curator.insert_evidence_item(item)
        notes.append(f"evidence {item.id}: {'created' if created else 'already existed (unchanged)'}")

    for entry in company_map_entries:
        created = curator.insert_company_map_entry(entry)
        notes.append(f"company_map {entry.id}: {'created' if created else 'already existed (unchanged)'}")

    return theme_created, notes


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backend", choices=("json", "sqlite", "postgres"), default=None)
    parser.add_argument("--cache-dir", default=None)
    parser.add_argument("--sqlite-path", default=None)
    parser.add_argument("--postgres-url", default=None)
    parser.add_argument("--confirm", action="store_true", help="Required to actually persist. Without it: dry run only.")
    parser.add_argument(
        "--set-visibility", nargs=2, metavar=("THEME_ID", "NEW_VISIBILITY"), default=None,
        help="Transition an existing theme's visibility (internal|ready_to_publish|published|archived). "
             "A separate, explicit action from authoring new content.",
    )
    return parser.parse_args(argv)


def _resolve_backend_settings(args: argparse.Namespace):
    settings = get_settings()
    backend = args.backend or settings.db_backend or "json"
    cache_dir = args.cache_dir or settings.cache_dir
    sqlite_path = args.sqlite_path or (str(settings.state_db_path) if settings.state_db_path else None)
    postgres_url = args.postgres_url or settings.state_db_url
    return backend, cache_dir, sqlite_path, postgres_url


def _run_set_visibility(args: argparse.Namespace) -> int:
    theme_id, raw_new_visibility = args.set_visibility
    try:
        new_visibility = ThemeVisibility(raw_new_visibility)
    except ValueError:
        print(f"Unrecognized visibility {raw_new_visibility!r}. Must be one of: "
              f"{', '.join(v.value for v in ThemeVisibility)}.")
        return 1

    backend, cache_dir, sqlite_path, postgres_url = _resolve_backend_settings(args)
    settings = Settings(
        db_backend=backend, cache_dir=Path(cache_dir) if cache_dir else Settings().cache_dir,
        state_db_path=Path(sqlite_path) if sqlite_path else None, state_db_url=postgres_url,
    )
    curator = backend_factory.get_theme_curator_repository(settings)

    current = curator.get_theme(theme_id)
    if current is None:
        print(f"No theme found with id {theme_id!r} — nothing to transition.")
        return 1

    allowed = _ALLOWED_VISIBILITY_TRANSITIONS.get(current.visibility, frozenset())
    if new_visibility not in allowed:
        print(
            f"Refusing transition {current.visibility.value!r} -> {new_visibility.value!r}: not an allowed "
            f"transition. Allowed from {current.visibility.value!r}: "
            f"{sorted(v.value for v in allowed) or 'none'}."
        )
        return 1

    if not args.confirm:
        print(f"Dry run (pass --confirm to apply): would transition theme {theme_id} "
              f"{current.visibility.value!r} -> {new_visibility.value!r}.")
        return 0

    updated_at = datetime.now(timezone.utc).isoformat()
    updated = curator.set_visibility(theme_id, new_visibility, updated_at)
    if updated is None:
        print(f"Transition failed for theme {theme_id} — no row updated.")
        return 1
    print(f"Theme {theme_id} is now {updated.visibility.value!r}.")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    if args.set_visibility is not None:
        return _run_set_visibility(args)

    built = build_authored_theme(AUTHORING_ENABLED)
    if built is None:
        print("AUTHORING_ENABLED is False — this script is disabled by default. Edit scripts/create_theme.py, "
              "fill in real content in place of every REPLACE_ME placeholder, and set AUTHORING_ENABLED = True "
              "before re-running.")
        return 0

    theme, evidence_items, company_map_entries = built
    if contains_placeholder_sentinel(theme, evidence_items, company_map_entries):
        print(f"Refusing to proceed: the authored content still contains the {_PLACEHOLDER_SENTINEL!r} placeholder "
              "in one or more fields. Replace every placeholder with real, checked content before running again.")
        return 1

    errors = validate_theme_content(theme, evidence_items, company_map_entries)
    if errors:
        print("Theme content is invalid — nothing was persisted. Issues:")
        for error in errors:
            print(f"  - {error}")
        return 1

    if not args.confirm:
        print("Dry run (pass --confirm to persist): content is well-formed and contains no placeholder text.")
        print(f"  Theme id: {theme.id} (initial visibility: {theme.visibility.value})")
        print(f"  Evidence items: {len(evidence_items)}")
        print(f"  Company map entries: {len(company_map_entries)}")
        print("  Note: this creates the theme at 'internal' visibility only. Publishing is a separate, "
              "explicit step: python -m scripts.create_theme --set-visibility <theme_id> ready_to_publish --confirm")
        return 0

    backend, cache_dir, sqlite_path, postgres_url = _resolve_backend_settings(args)
    theme_created, notes = persist_theme(
        theme, evidence_items, company_map_entries, backend,
        cache_dir=cache_dir, sqlite_path=sqlite_path, postgres_url=postgres_url,
    )
    for note in notes:
        print(note)
    return 0 if theme_created else 1


if __name__ == "__main__":
    sys.exit(main())
