"""EevaResearch Phase 4, Step 3B (design/DECISIONS.md) — a private,
operator-only, one-off authoring pathway for a single manually curated
Research Case bundle. This is not a product feature: no application
runtime module (app.py, any src/ui page, Radar, Daily News, a pipeline,
a worker, or a scheduler) imports this script, and it is never invoked
automatically by anything in this repository.

Invoke as (from the repo root):

    python -m scripts.create_research_case --confirm [--backend json|sqlite|postgres]

Safety gates (both must be satisfied, independently, before anything is
ever persisted):

  1. AUTHORING_ENABLED below defaults to False. An operator must
     deliberately edit this file and change it to True before this
     script will ever consider persisting anything — a plain
     `python -m scripts.create_research_case` run, with no edits at all,
     always exits 0 having written nothing, regardless of any CLI flag.
  2. Even with AUTHORING_ENABLED = True, the `--confirm` CLI flag is
     also required. Without it, the script only builds and validates the
     authored bundle and prints what it *would* do — a dry run, never a
     write.

The authored bundle itself lives in the clearly marked "OPERATOR-AUTHORED
CASE CONTENT" section below — every field the operator must personally
fill in from a real, checked source is a literal `_PLACEHOLDER_SENTINEL`
string by default. persist_bundle() refuses to persist a bundle that
still contains that sentinel anywhere, as a second, content-level
safeguard independent of AUTHORING_ENABLED/--confirm — this script can
never accidentally represent the shipped placeholder text as a real
case, even if both gates above were somehow satisfied without the
operator actually replacing the placeholder content.

This script performs no I/O beyond the one local storage backend it is
explicitly pointed at: no network call, no source fetch, no LLM/model
call, no scan, no discovery, no translation, no notification. It
constructs the bundle only through the existing, unmodified
build_research_case_bundle()/validate_research_case_bundle() (Phase 4,
Step 2) and persists only through the existing, unmodified atomic
bundle-persistence functions (Phase 4, Step 3B) — it duplicates no
model, validation, or persistence logic of its own.

Deterministic ids only: every id below comes from the existing
build_case_id()/build_evidence_id()/build_relationship_assertion_id()/
build_dependency_assertion_id() factories, derived from the authored
content itself — never a random value, never wall-clock time. Re-running
this script with identical authored content always re-derives the exact
same ids, so a second run safely no-ops via the atomic persistence
functions' own duplicate-id detection rather than needing any separate
idempotency mechanism here.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from src.config.settings import get_settings
from src.data_access import research_store
from src.data_access.postgres_state_db import connection as postgres_connection
from src.data_access.postgres_state_db import research_repository as postgres_research_repository
from src.data_access.postgres_state_db import schema as postgres_schema
from src.data_access.state_db import connection as sqlite_connection
from src.data_access.state_db import research_repository as sqlite_research_repository
from src.data_access.state_db import schema as sqlite_schema
from src.logic.research_case_validation import (
    ResearchCaseBundle,
    build_research_case_bundle,
    validate_research_case_bundle,
)
from src.models.research_case import (
    AssertionConfidence,
    AssertionStatus,
    BottleneckType,
    DependencyAssertion,
    RelationshipAssertion,
    RelationshipRole,
    ResearchCase,
    ResearchCaseStatus,
    ResearchEvidenceItem,
)

# =============================================================================
# SAFETY GATE 1 of 2 — see module docstring. Must be hand-edited to True.
# =============================================================================
AUTHORING_ENABLED = False

# A literal sentinel an operator must replace with real, checked content.
# persist_bundle() refuses to write anything containing this string —
# SAFETY GATE independent of AUTHORING_ENABLED/--confirm (see docstring).
_PLACEHOLDER_SENTINEL = "REPLACE_ME"

# =============================================================================
# OPERATOR-AUTHORED CASE CONTENT — edit every _PLACEHOLDER_SENTINEL value
# below with real, checked, caller-verified content before setting
# AUTHORING_ENABLED = True. Timestamps must be authored (a real moment
# you are recording this), never generated by this script.
# =============================================================================

_CASE_CREATED_AT = _PLACEHOLDER_SENTINEL  # e.g. "2026-08-20T00:00:00+00:00"
_CASE_TRIGGER_SOURCE_TYPE = _PLACEHOLDER_SENTINEL  # e.g. "radar" or "daily_news"
_CASE_TRIGGER_SOURCE_ID = _PLACEHOLDER_SENTINEL  # the real CandidateSignal/NewsStory id this case was triggered from
_CASE_TRIGGER_SOURCE_NAME = _PLACEHOLDER_SENTINEL  # e.g. the issuer's display name
_CASE_TRIGGER_SUMMARY = _PLACEHOLDER_SENTINEL
_CASE_TITLE = _PLACEHOLDER_SENTINEL
_CASE_RESEARCH_QUESTION = _PLACEHOLDER_SENTINEL


def _build_evidence_specs() -> list[dict]:
    """One dict per ResearchEvidenceItem to create. Edit/add entries;
    every value must be real, checked content — never invented."""
    return [
        {
            "source_type": _PLACEHOLDER_SENTINEL,
            "source_id": _PLACEHOLDER_SENTINEL,
            "source_url": _PLACEHOLDER_SENTINEL,
            "source_publisher_or_system": _PLACEHOLDER_SENTINEL,
            "source_date": _PLACEHOLDER_SENTINEL,
            "retrieved_at": _PLACEHOLDER_SENTINEL,
            "excerpt_original": _PLACEHOLDER_SENTINEL,
            "original_language": _PLACEHOLDER_SENTINEL,
            "added_at": _PLACEHOLDER_SENTINEL,
        },
    ]


def build_authored_bundle(enable_authoring: bool = AUTHORING_ENABLED) -> ResearchCaseBundle | None:
    """Pure, no I/O. Returns None when `enable_authoring` is False (the
    default) — the caller must not proceed to validation/persistence in
    that case. Returns the constructed (not yet validated) bundle
    otherwise. `enable_authoring` is a parameter (not a bare module-level
    read) specifically so tests can exercise both branches without
    needing to edit this file."""
    if not enable_authoring:
        return None

    case_id = research_store.build_case_id(_CASE_TRIGGER_SOURCE_TYPE, _CASE_TRIGGER_SOURCE_ID, _CASE_CREATED_AT)
    case = ResearchCase(
        id=case_id,
        trigger_source_type=_CASE_TRIGGER_SOURCE_TYPE,
        trigger_source_id=_CASE_TRIGGER_SOURCE_ID,
        trigger_source_name=_CASE_TRIGGER_SOURCE_NAME,
        trigger_summary=_CASE_TRIGGER_SUMMARY,
        title=_CASE_TITLE,
        research_question=_CASE_RESEARCH_QUESTION,
        status=ResearchCaseStatus.OPEN,
        created_at=_CASE_CREATED_AT,
        version=1,
    )

    evidence_items = []
    for spec in _build_evidence_specs():
        evidence_id = research_store.build_evidence_id(case_id, spec["source_type"], spec["source_id"], spec["added_at"])
        evidence_items.append(ResearchEvidenceItem(
            id=evidence_id, case_id=case_id,
            source_type=spec["source_type"], source_id=spec["source_id"], source_url=spec["source_url"],
            source_publisher_or_system=spec["source_publisher_or_system"], source_date=spec["source_date"],
            retrieved_at=spec["retrieved_at"], excerpt_original=spec["excerpt_original"],
            original_language=spec["original_language"], added_at=spec["added_at"],
        ))

    # No assertion is authored by default — an operator adds one here
    # (a RelationshipAssertion and/or DependencyAssertion, referencing
    # evidence_items[i].id) only once real evidence exists above.
    assertions: list[RelationshipAssertion | DependencyAssertion] = []

    return build_research_case_bundle(case, evidence_items, assertions)


def _bundle_field_values(bundle: ResearchCaseBundle) -> list[object]:
    """Every free-text-shaped field this script itself authored, for the
    placeholder-sentinel scan below — deliberately not every field on
    every dataclass (enum/id/tuple-of-id fields can't meaningfully
    contain the sentinel), just the ones an operator fills in by hand."""
    values: list[object] = [
        bundle.case.trigger_source_type, bundle.case.trigger_source_id, bundle.case.trigger_source_name,
        bundle.case.trigger_summary, bundle.case.title, bundle.case.research_question, bundle.case.created_at,
    ]
    for item in bundle.evidence_items:
        values.extend([
            item.source_type, item.source_id, item.source_url, item.source_publisher_or_system,
            item.source_date, item.retrieved_at, item.excerpt_original, item.original_language, item.added_at,
        ])
    for assertion in bundle.assertions:
        values.append(assertion.reasoning)
        values.extend(assertion.limitations)
        if isinstance(assertion, RelationshipAssertion):
            values.extend([assertion.subject_entity, assertion.object_entity, assertion.created_at])
        else:
            values.extend([assertion.affected_entity, assertion.created_at])
            if assertion.transmission_path is not None:
                values.extend(assertion.transmission_path)
    return values


def contains_placeholder_sentinel(bundle: ResearchCaseBundle) -> bool:
    return any(isinstance(value, str) and _PLACEHOLDER_SENTINEL in value for value in _bundle_field_values(bundle))


def persist_bundle(
    bundle: ResearchCaseBundle,
    backend: str,
    cache_dir: Path | None = None,
    sqlite_path: str | None = None,
    postgres_url: str | None = None,
) -> bool:
    """Dispatches to the one atomic bundle-persistence function for the
    explicitly requested backend. Never reads settings itself (main()'s
    job) — every configuration input is an explicit argument, so this
    function is directly testable against a tmp_path/in-memory
    connection without touching real state."""
    if backend == "json":
        assert cache_dir is not None
        return research_store.append_research_case_bundle(cache_dir, bundle)
    if backend == "sqlite":
        assert sqlite_path is not None
        conn = sqlite_connection.connect(Path(sqlite_path))
        sqlite_schema.migrate(conn)
        return sqlite_research_repository.insert_research_case_bundle(conn, bundle)
    if backend == "postgres":
        assert postgres_url is not None
        conn = postgres_connection.connect(postgres_url)
        postgres_schema.migrate(conn)
        return postgres_research_repository.insert_research_case_bundle(conn, bundle)
    raise ValueError(f"Unsupported backend: {backend!r}")


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backend", choices=("json", "sqlite", "postgres"), default=None, help="Overrides EDGE_DB_BACKEND for this one invocation only.")
    parser.add_argument("--cache-dir", default=None, help="Overrides the JSON backend's cache directory (default: Settings.cache_dir).")
    parser.add_argument("--sqlite-path", default=None, help="Overrides the SQLite backend's database path (default: Settings.state_db_path).")
    parser.add_argument("--postgres-url", default=None, help="Overrides the Postgres backend's connection URL (default: Settings.state_db_url).")
    parser.add_argument("--confirm", action="store_true", help="Required to actually persist. Without it, this is a dry run: build, validate, print — never write.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    bundle = build_authored_bundle(AUTHORING_ENABLED)
    if bundle is None:
        print("AUTHORING_ENABLED is False — this script is disabled by default. Edit scripts/create_research_case.py, "
              "fill in real content in place of every REPLACE_ME placeholder, and set AUTHORING_ENABLED = True before re-running.")
        return 0

    if contains_placeholder_sentinel(bundle):
        print(f"Refusing to proceed: the authored bundle still contains the {_PLACEHOLDER_SENTINEL!r} placeholder "
              "in one or more fields. Replace every placeholder with real, checked content before running again.")
        return 1

    validation_errors = validate_research_case_bundle(bundle)
    if validation_errors:
        print("Bundle is invalid — nothing was persisted. Validation errors:")
        for error in validation_errors:
            location = f" [{error.record_type} {error.record_id}]" if error.record_type else ""
            print(f"  - {error.code}{location}: {error.message}")
        return 1

    if not args.confirm:
        print("Dry run (pass --confirm to persist): bundle is well-formed and contains no placeholder content.")
        print(f"  Case id: {bundle.case.id}")
        print(f"  Evidence items: {len(bundle.evidence_items)}")
        print(f"  Assertions: {len(bundle.assertions)}")
        return 0

    settings = get_settings()
    backend = args.backend or settings.db_backend or "json"
    cache_dir = Path(args.cache_dir) if args.cache_dir else settings.cache_dir
    sqlite_path = args.sqlite_path or (str(settings.state_db_path) if settings.state_db_path else None)
    postgres_url = args.postgres_url or settings.state_db_url

    persisted = persist_bundle(bundle, backend, cache_dir=cache_dir, sqlite_path=sqlite_path, postgres_url=postgres_url)
    if persisted:
        print(f"Persisted case {bundle.case.id} ({len(bundle.evidence_items)} evidence item(s), "
              f"{len(bundle.assertions)} assertion(s)) to backend={backend!r}.")
        return 0

    print(f"Nothing was persisted for case {bundle.case.id} — the case id, or one of its evidence/assertion ids, "
          f"already exists in backend={backend!r} (or the write failed). No existing record was changed.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
